# Generated by Django 5.1.15 on 2026-09-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='clientes',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='clientes',
            field=models.ManyToManyField(related_name='cuenta', to='gestion.cliente'),
        ),
    ]
