# Generated by Django 5.1.15 on 2026-09-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_cuenta_clientes_cuenta_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], default='natural', max_length=10),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='clientes',
            field=models.ManyToManyField(related_name='cuentas', to='gestion.cliente'),
        ),
    ]
