# Generated by Django 5.1.15 on 2026-09-28 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_cliente_tipo_cliente_alter_cuenta_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='etiqueta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas', to='gestion.etiqueta'),
        ),
    ]
