# Generated by Django 5.1.15 on 2026-09-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_perfilcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
