# Generated by Django 5.1.15 on 2026-10-02 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_cuenta_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='cuenta_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_recibidas', to='gestion.cuenta'),
        ),
    ]
